### ISSUE TITLE
Latest build linking pugixml 1.14 instead the "pinned" version pugixml 1.13 ?

### ISSUE THREAD

**Issue by traversaro** [conda-forge/openvino-feedstock#52]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I encountered some strange conda environment solution failures (see https://github.com/ami-iit/ironcub_mk1_software/issues/11#issuecomment-1802102145), and I tracked them to the fact that for some reason the latest build of openvino packages used pugixml 1.14, instead of pugixml 1.13 that should be pinned after https://github.com/conda-forge/openvino-feedstock/pull/37 . 

Latest build (`2023.1.0=*_1`), with pugixml 1.14 : https://conda-metadata-app.streamlit.app/?q=conda-forge%2Fwin-64%2Flibopenvino-hetero-plugin-2023.1.0-h63175ca_1.conda
Previous build (`2023.1.0=*_0`), correctly linking pugixml 1.13 : https://conda-metadata-app.streamlit.app/?q=conda-forge%2Fwin-64%2Flibopenvino-hetero-plugin-2023.1.0-h63175ca_0.conda .

@conda-forge/openvino do you have any idea what could be going on? I checked the recipe file and I could not find anything wrong at the first glance.

### Installed packages

```shell
Not relevant, however a related output is:

C:\Users\straversaro>mamba create -n test125 libopenvino-dev=2023.1.0=*_1 ogre=1.10.12=*_15

Looking for: ['libopenvino-dev==2023.1.0[build=*_1]', 'ogre==1.10.12[build=*_15]']

conda-forge/win-64                                          Using cache
conda-forge/noarch                                          Using cache
Could not solve for environment specs
The following packages are incompatible
├─ libopenvino-dev 2023.1.0 *_1 is installable and it requires
│  └─ libopenvino-hetero-plugin 2023.1.0 h63175ca_1, which requires
│     └─ pugixml >=1.14,<1.15.0a0 , which can be installed;
└─ ogre 1.10.12 *_15 is not installable because it requires
   └─ pugixml >=1.13,<1.14.0a0 , which conflicts with any installable versions previously reported.
```

### Environment info

```shell
C:\Users\straversaro>conda info

     active environment : None
            shell level : 0
       user config file : C:\Users\straversaro\.condarc
 populated config files : C:\Users\straversaro\AppData\Local\miniforge3\.condarc
                          C:\Users\straversaro\.condarc
          conda version : 23.7.3
    conda-build version : 3.26.1
         python version : 3.10.12.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.2=0
                          __win=0=0
       base environment : C:\Users\straversaro\AppData\Local\miniforge3  (writable)
      conda av data dir : C:\Users\straversaro\AppData\Local\miniforge3\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : C:\Users\straversaro\AppData\Local\miniforge3\pkgs
                          C:\Users\straversaro\.conda\pkgs
                          C:\Users\straversaro\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\straversaro\AppData\Local\miniforge3\envs
                          C:\Users\straversaro\.conda\envs
                          C:\Users\straversaro\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.7.3 requests/2.31.0 CPython/3.10.12 Windows/10 Windows/10.0.22621
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by ilya-lavrenov** [comment]
Looks like conda ignores pinned dependencies during installation on build stage..
https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/818763/logs/43

**Comment by traversaro** [comment]
I have no idea why that is happening to be honest. Probably it is better to proceed with https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5130 as soon as possible to fix this issue.

**Comment by traversaro** [comment]
It is not clear what happened, but anyhow the fact that pugixml 1.14 is used is appropriate after https://github.com/conda-forge/openvino-feedstock/pull/56 .
