### ISSUE TITLE
Unvendor more dependencies

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/openvino-feedstock#67]
### Comment:

Thank you for unvendoring libprotouf 

Is there a way we can unvendor the easier dependencies that we have built at conda-forge?

I'm not too sure the best way to go about it for the given build system, but the easy ones that come to mind are

* [nlohmann_json](https://github.com/conda-forge/nlohmann_json-feedstock)
* [zlib](https://github.com/conda-forge/zlib-feedstock/)

Thank you for considering this.

**Comment by ilya-lavrenov** [comment]
Hi @hmaarrfk 

These dependencies (as well as gflags) are used only test sub-packages tests:
https://github.com/conda-forge/openvino-feedstock/blob/95cc49df58259251d838829da33755661388ca89/recipe/meta.yaml#L603-L608

References to original OpenVINO code:
- https://github.com/openvinotoolkit/openvino/blob/master/thirdparty/dependencies.cmake#L122-L136
- https://github.com/openvinotoolkit/openvino/blob/master/thirdparty/dependencies.cmake#L263-L270

So, I suppose it's harmless to keep them as is. Maybe we just can add comments for other maintainers

**Comment by hmaarrfk** [comment]
honestly, its somewhat against conda-forge best practices.

> So, I suppose it's harmless to keep them as is.

for zlib and json maybe, but the onnx dependency looks like it is used for linking the runtime.

Ultimately, it would be good to move to remove these from appearing in the recipe.
They add extra long term maintenance and make it difficult to use this recipe as a "reference" for others.

**Comment by ilya-lavrenov** [comment]
> for zlib and json maybe,

addressed here https://github.com/conda-forge/openvino-feedstock/pull/71 

> but the onnx dependency looks like it is used for linking the runtime.

it would be great to finish this PR https://github.com/conda-forge/onnx-feedstock/pull/106 then

**Comment by hmaarrfk** [comment]
Windows struck again on that one

**Comment by ilya-lavrenov** [comment]
@hmaarrfk some vendored dependencies were removed. Thanks for your advices!

**Comment by hmaarrfk** [comment]
do feel free to help on the onnx front. my intentions are to help there, just you know, I'm not a full on expert in windows.
